avitto/avitto/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf.urls import handler404, url
from django.conf.urls.static import static


urlpatterns = [
    url(r'admin/', admin.site.urls),
    path('', include('core.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)  # маршрут для отладочного режима

# handler404 = pageNotFound

avitto/core/urls.py
from django.conf.urls import url
from django.urls import path, include
from django.views.generic import TemplateView

from .views import (CategoriesDetailView, PostShare,
                    IndexView, AllPostView, PostCreateView, AllCategoryView, PostDelete, EditView, PostDetailView)

from .urls_auth import urlpatterns as auth_patterns
app_name = 'core'

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    path('posts/<int:post_id>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/create/', PostCreateView.as_view(), name='post_create'),
    path('posts/all_posts/', AllPostView.as_view(), name='all_posts'),
    path('posts/<int:post_id>/delete/', PostDelete.as_view(), name='post_delete'),
    path('posts/<int:post_id>/delete-success/',
         TemplateView.as_view(template_name='core/delete_success.html'), name='post_delete_success'),
    path('posts/<int:post_id>/edit/', EditView.as_view(), name='post_edit'),

    path('category/', AllCategoryView.as_view(), name='category_all'),
    path('category/<int:category_id>/',
         CategoriesDetailView.as_view(), name='category_detail'),
    path('posts/<int:post_id>/share/', PostShare.as_view(), name='post_share'),



]


urlpatterns += auth_patterns

avitto/core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from .validators import validate_date_edit, validate_birth_date
from django.urls import reverse
from django.template.defaultfilters import slugify


# Create your models here.


def user_foto_path(instance, filename):
    return 'user_{0}/foto/{1}'.format(instance.user.id, filename)


def user_directory_path(instance, filename):
    return 'user_{0}/posts/{1}'.format(instance.author.id, filename)


class Profile(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='profile', verbose_name='пользователь')
    about = models.TextField(max_length=500, verbose_name='немного о себе')
    foto = models.ImageField(upload_to=user_foto_path,
                             verbose_name='фото пользователя')
    birth_date = models.DateField(
        null=True, blank=True, verbose_name='день рождения', validators=[validate_birth_date, ])
    post = models.ForeignKey(
        'Post', on_delete=models.PROTECT, null=True, blank=True, related_name='post', verbose_name='объявления пользователя')

    def __str__(self) -> str:
        return str(self.user.username)

    class Meta:
        verbose_name = 'профиль пользователя'
        verbose_name_plural = 'список профилей пользователя'


class Category(models.Model):
    category_name = models.CharField(
        max_length=100, verbose_name='наименование категории', db_index=True)
    description = models.TextField(
        max_length=1000, blank=True, verbose_name='описание категории')
    # post = models.ManyToManyField(
    #     'Post', related_name='post_category',  verbose_name='объявления пользователя', blank=True)
    # author = models.ManyToManyField(
    #     'Profile',   related_name='author', verbose_name='автор объявления', blank=True)

    def __str__(self) -> str:
        return '{}'.format(self.category_name)

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'список категорий'
        ordering = ['category_name']


class Post(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='user', verbose_name='пользователь')
    post_name = models.CharField(
        max_length=100, verbose_name='наименование объявления')
    description = models.TextField(
        max_length=1000, blank=True, verbose_name='содержание объявления')
    image = models.ImageField(
        upload_to=user_directory_path, verbose_name='фотография товара')
    date_pub = models.DateTimeField(
        auto_now_add=True, verbose_name='дата создания')  # (auto_now_add=True)
    date_edit = models.DateTimeField(
        auto_now=True, verbose_name='дата изменения', validators=[validate_date_edit])  # (auto_now=True)
    price = models.DecimalField(
        verbose_name='цена товара', max_digits=10, decimal_places=2)
    category = models.ForeignKey(
        Category, on_delete=models.PROTECT, null=True, blank=True, related_name='category', verbose_name='категория товара')
    draft = models.BooleanField("Черновик", default=False)
    slug = models.SlugField(
        max_length=250, unique_for_date='date_pub')

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self) -> str:
        return '(Пользователь {}: {},  цена: {})'.format(self.author.username, self.post_name, self.price, )

    # def get_absolute_url(self):
    #     return reverse('core:post_detail', kwargs={'pk': self.pk})

    def get_absolute_url(self):
        return reverse('core:post_detail', args=[str(self.id)])

    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return '#'

    class Meta:
        verbose_name = 'объявление'
        verbose_name_plural = 'список объявлений'
        # порядок сортировки с минусом в обратную сторону
        ordering = ['-category', '-date_pub']


class Comment(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='пользователь')
    timestamp = models.DateTimeField(
        default=timezone.now, verbose_name='время')
    content = models.TextField(
        max_length=700, blank=False, verbose_name='содержимое')
    post = models.ForeignKey(
        Post, related_name='comments', on_delete=models.CASCADE, verbose_name='объявление')

    def __str__(self):
        return "{0} : {1}".format(self.user, self.content[:10] + "...")

    class Meta:
        verbose_name = 'комметарии'
        verbose_name_plural = 'список комментариев'
        ordering = ['-timestamp', ]

#
# def get_image_filename(instance, filename):
#     author = instance.post.author.id
#     name = instance.post.post_name
#     slug = slugify(name)
#     return 'user_{0}/posts/{1}/images{2}'.format(author, name, slug, filename)
#
#
# class Image(models.Model):
#     image = models.ImageField(
#         upload_to=get_image_filename, null=True, blank=True, verbose_name='изображение галереи')
#     post = models.ForeignKey(
#         Post, on_delete=models.CASCADE, related_name="post_images", default=None, verbose_name='изображения к объявлению')
#
#     def __str__(self) -> str:
#         return '(Объявление {}: {} )'.format(self.post, self.image)
#
#     @property
#     def image_url(self):
#         if self.image and hasattr(self.image, 'url'):
#             return self.image.url
#         else:
#             return '#'

avitto/core/views.py
from django.http.response import Http404, HttpResponseRedirect
from django.utils import timezone
from django.db.models.aggregates import Sum
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.forms.models import modelform_factory, modelformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.template import Context, context, loader
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import ListView, CreateView, DeleteView, UpdateView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView, View
from .models import Post, Category, Profile, Comment
from .forms import PostForm, EmailPostForm, CommentForm
from django.forms import modelformset_factory
from avitto.settings import FROM_EMAIL, EMAIL_ADMIN


# Create your views here.


class IndexView(ListView):
    model = Post
    template_name = 'core/index.html'
    context_object_name = 'posts'
    extra_context = {'page_title': 'Главная'}
    queryset = model.objects.all().filter(
        draft=False).order_by('-date_edit')[:12]
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


class AllPostView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'core/all_posts.html'
    extra_context = {'page_title': 'Все объявления'}
    queryset = model.objects.all().order_by(
        '-date_edit').filter(draft=False)
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


# def all_posts(request):
#     # все посты
#     posts = Post.objects.all().order_by('category')
#     context = {
#         'posts': posts,
#         'title': "Все объявления"}
#     return render(request, template_name='core/all_posts.html', context=context)

class PostDetailView(DetailView):
    model = Post
    comment_form = CommentForm
    pk_url_kwarg = "post_id"
    template_name = 'core/post_detail.html'
    extra_context = {'page_title': 'Подробнее об объявлении'}

    def get(self, request, post_id, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        # context['images'] = Image.objects.filter(post_id=post_id)
        # context['images_all'] = Image.objects.all()
        context['posts'] = Post.objects.filter(draft=True)
        context['categories'] = Category.objects.all()
        context['comments'] = Comment.objects.filter(
            post__pk=post_id).order_by('-timestamp')
        context['comment_form'] = None
        if request.user.is_authenticated:
            context['comment_form'] = self.comment_form
        return self.render_to_response(context)

    @method_decorator(login_required)
    def post(self, request, post_id, *args, **kwargs):
        post = get_object_or_404(Post, id=post_id)
        form = self.comment_form(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.timestamp = timezone.now()
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect('core:post_detail', post_id)
        else:
            return render(request=request, template_name=self.template_name, context={'comment_form': form,
                                                                                      'post': post,
                                                                                      'categories': Category.objects.all(),
                                                                                      #   'images': Image.objects.filter(post_id=post_id),

                                                                                      })
# def post_detail(request, post_id):
#     # детали поста
#     post = get_object_or_404(Post, id=post_id)
#     context = {
#         'post': post,
#         'title': ("Подробнее об: {}".format(post.post_name))}
#     return render(request, template_name='core/post_detail.html', context=context)


class PostCreateView(CreateView):
    form_class = PostForm
    template_name = 'core/post_create.html'
    login_url = '/admin/login'
    extra_context = {'page_title': 'Создать объявление'}

    # def get(self, request,  *args, **kwargs):
    #     ImageFormSet = modelformset_factory(Image, form=ImageForm, extra=3)
    #     print('ok1')
    #     if request.method == "GET":
    #         print('ok2')
    #         form = PostForm()
    #         formset = ImageFormSet(queryset=Image.objects.none())
    #         print('ok2-1')
    #         return render(request, self.template_name,  {"form": form, "formset": formset})
    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect(reverse('core:post_detail', kwargs={'post_id': post.id}))
        else:
            return render(request, 'core/post_create.html', {
                'form': form})
    # @ method_decorator(login_required)
    # def post(self, request,  *args, **kwargs):
    #     # form = self.form_class(request.POST, request.FILES)
    #     # if form.is_valid():
    #     #     post = form.save(commit=False)
    #     #     post.author = request.user
    #     #     post.save()
    #     #     return redirect(reverse('core:post_detail', kwargs={'post_id': post.id, }))
    #     # else:
    #     #     return render(request, 'core/post_create.html', {
    #     #         'form': form})
    #     ImageFormSet = modelformset_factory(Image, form=ImageForm, extra=3)
    #     if request.method == 'POST':
    #         form = PostForm(request.POST, request.FILES)
    #         formset = ImageFormSet(request.POST, request.FILES,
    #                                queryset=Image.objects.none())
    #         print('ok3')
    #         if form.is_valid() and formset.is_valid():
    #             post = form.save(commit=False)
    #             post.author = request.user
    #             post.save()
    #             print('ok4')
    #             for form_img in formset.cleaned_data:
    #                 print('ok5')
    #                 if form_img:
    #                     print('ok6')
    #                     image = form_img['image']
    #                     photo = Image(post=post, image=image)
    #                     photo.save()
    #                     print('ok6:')
    #             # use django messages framework
    #             messages.success(request,
    #                              "Yeeew, check it out on the home page!")

    #             return redirect(reverse('core:post_detail', kwargs={'post_id': post.id, }))
    #         else:
    #             print('postForm.errors: ', form.errors,
    #                   'formset.errors: ', formset.errors)
    #             print('ok7')
    #     else:
    #         form = PostForm()
    #         formset = ImageFormSet(queryset=Image.objects.none())
    #         print('ok8')
    #     return render(request, 'core/post_create.html',
    #                   {'postForm': form, 'formset': formset})


# def post_create(request):
#     if request.method == 'GET':
#         form = PostForm()
#         return render(request, 'core/post_create.html', {
#             'form': form})
#     elif request.method == "POST":
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             return redirect(reverse('core:post_detail', kwargs={'post_id': post.id}))
#         else:
#             return render(request, 'core/post_create.html', {
#                 'form': form})
        # return HttpResponse('post_create')

class PostDelete(DeleteView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'core/post_delete.html'
    extra_context = {'page_title': 'Удалить объявление'}

    def get_success_url(self):
        post_id = self.kwargs['post_id']
        return reverse('core:post_delete_success', args=(post_id, ))


class EditView(UpdateView):
    model = Post
    pk_url_kwarg = 'post_id'
    template_name = 'core/post_edit.html'
    form_class = PostForm
    extra_context = {'page_title': 'Изменить объявление'}

    def get_success_url(self):
        post_id = self.kwargs['post_id']
        return reverse('core:post_detail', args=(post_id, ))


class CategoriesDetailView(DetailView):
    model = Category
    pk_url_kwarg = "category_id"
    template_name = 'core/cat_detail.html'
    extra_context = {'page_title': 'Об категории'}

    def get(self, request, category_id, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['posts'] = Post.objects.filter(category_id=category_id)
        context['category'] = Category.objects.get(pk=category_id)
        context['categories'] = Category.objects.all()

        return self.render_to_response(context)


# def category_detail(request, category_id):
#     posts = Post.objects.filter(category_id=category_id)
#     categories = Category.objects.all()
#     category = Category.objects.get(pk=category_id)
#     context = {
#         'posts': posts,
#         'categories': categories,

avitto/core/templates/core/all_posts.html
{% extends 'base.html' %} {% load my_filters %}
{% block title %}
<title>{{page_title}}</title>
{% endblock title %}
<p>{%block content %}
  <header>
      <h1>Все объявления</h1>
    </header>
    <!-- /Header -->
    <section>
      {% if posts %}
        <ul class="posts_list">
          {% for post in posts %}
           <li>
            <a href="{% url 'core:post_detail' post.id %}" class="image_card">
               <p> {{ post.post_name }}</p>
               <img src="{{ post.image_url }}" alt="{{ post.post_name}}" />
               
               <p>Стоимость: {{ post.price|currency}} рублей</p>
               <p>Категория объявления: {{post.category}}</p>
            </a>            
           </li>               
          {% endfor %}
        </ul>
        {% endif %}
    </section>
  {% include "pagination.html" with page=posts %}       
{% endblock content%}</p>

avitto/core/templates/core/cat_detail.html
{% extends 'base.html' %} {% load my_filters %}{% block title %}
<title>{{page_title}}</title>
{% endblock title %}
<p>{%block content %}
  
  <section class="category_det-main">
    <article class="category_posts">{% if categories %}
        <ul class="category_mainpage">
          {% for category in categories %}
          <li>
            <a href="{% url 'core:category_detail' category.id %}"
              >{{ category.category_name|linebreaks }}</a
            >
          </li>
          {% endfor %}         
        </ul>
      {% endif %}
    </article>    
    <article class="posts">
        <h2>Самые последние из размещенных объявлений из категории: </h2>
        <p><a href="{% url 'core:category_detail' category.id %}"
              >{{ category.category_name }}</a
            ></p>
        <p><a href="{% url 'core:category_detail' category.id %}"
              >{{ category.description }}</a
            >    </p>
        
         {% if posts %}
        <ul class="posts_list">
          {% for post in posts %}
           <li>
            <a href="{% url 'core:post_detail' post.id %}" class="image_card">
               <p> {{ post.post_name }}</p>
               <img src="{{ post.image_url }}" alt="{{ post.post_name}}" />
               <p>Дата последнего изменения: {{ post.date_edit }}</p>
               <p>Стоимость: {{ post.price|currency }} рублей</p>
               <p>Категория объявления: {{post.category}}</p>
            </a>            
           </li>               
          {% endfor %}
        </ul>
        {% endif %}
    </article>
  </section>
   
{% endblock content%}</p>

avitto/core/templates/core/categories.html
{% extends 'base.html' %} {% block title %}
<title>{{page_title}}</title>
{% endblock title %}
<p>{%block content %} 
  <h1>Категории в которых Вы можете создать свои объявления</h1>     
      <section class="category">
      {% if categories %}
        <ul>
          {% for category in categories %}
          <li>
            <a href="{% url 'core:category_detail' category.id %}"
              >{{ category.category_name|linebreaks }}</a
            >
          </li>
          {% endfor %}         
        </ul>
      {% endif %}
      </section>
{% endblock content%}</p>

avitto/core/templates/core/delete_success.html
{% extends 'base.html' %} {% block title %}
<title>Категории</title>
{% endblock title %}
<p>{%block content %} 
   <header class="header category_del">
      <h1>{{ title }}</h1>
      <h2>Ваше объявление удалено!</h2>
      <section class="category category_del">
        <!-- <a href="{% url 'core:category_all' %}" class="all-category"
          >Перейти к просмотру всех категорий</a
        > -->
        {% if categories %}
        <ul>
          {% for category in categories %}
          <li>
            <a href="{% url 'core:category_detail' category.id %}"
              >{{ category.category_name }}</a
            >
          </li>
          <li>{{ category.description }}</li>
         
          {% endfor %}
        
        </ul>
        {% endif %}
      </section>
      <a href="{% url 'core:all_posts' %}" class="posts"
        >Перейти к просмотру всех объявлений</a
      >
    
      <a href="{% url 'core:post_create' %}" class="post-create"
        >Cоздать объявление</a
      >
     
      <a href="{% url 'core:index' %}"> На главную </a>
    </header>
    <!--  /HEADER -->
    <main></main>
    <!--  /MAIN -->
    <footer></footer>
    <!--  /foooter -->
  {% endblock content%}</p>

avitto/core/templates/core/index.html
{% extends 'base.html' %} 
 {% block title %}
    <title>{{page_title}}</title>
  {% endblock title %}  
 
   <p>{%block content %}     
     <h1 class="title_page">
          Добро пожаловать на сайт бесплатных объявлений
      </h1> 
      <h2>Самые последние из размещенных объявлений:</h2>      
       <ul class="category_mainpage">
          {% for cat in category %}
          <li>
            <a href="{% url 'core:category_detail' cat.id %}">{{ cat.category_name }}</a>
          </li>
          {% endfor %}
        </ul>                      
      <section class="posts">        
        {% if posts %}
        <ul class="posts_list">
          {% for post in posts %}
           <li>
            <a href="{% url 'core:post_detail' post.id %}" class="image_card">
               <p> {{ post.post_name }}</p>
               <img src="{{ post.image_url }}" class="image_card" alt="{{ post.post_name}}" />             
               <p>Дата последнего изменения: {{ post.date_edit }}</p>
               <p>Стоимость: {{ post.price }} рублей</p>
               <p>Категория объявления: {{post.category}}</p>
                <a href="{% url 'core:profile' post.author.id %}">Продавец: {{post.author.username}} </a>
            </a>            
           </li>               
          {% endfor %}
        </ul>
        {% endif %}
      </section>  
    {% include "pagination.html" with page=posts %}
{% endblock content%}</p>

avitto/core/templates/core/post_create.html
{% extends 'base.html' %} {% block title %}
<title>{{page_title}}</title>
{% endblock title %}
<p>{%block content %}
{% if user.is_authenticated %}
    <form method="POST" enctype="multipart/form-data" class="post-form">
      {% csrf_token %}
       
     
   {% for field in form %}
      <p>{{ field.label }}</p>
      <p>{{ field }}</p>
      {% endfor %}
<!-- -->
<!--    {{ formset.management_form }}-->
<!--    {% for form in formset %}-->
<!--        {{ form.as_p }}-->
<!--    {% endfor %}-->
       <button type="submit" class="button">Разместить объявление</button>
    </form>
{% else %}
    <h3> Чтобы создавать объявления, вам нужно </h3>
    <a href="{% url 'core:login' %}" class="button"> ВОЙТИ </a> 
    <hr>
    <h3>или</h3>
    <a href="{% url 'core:sighup' %}" class="button"> зарегистрироваться </a>
{% endif %}    
{% endblock content%}</p>

avitto/core/templates/core/post_delete.html
{% extends 'base.html' %} {% block title %}
<title>{{page_title}}</title>
{% endblock title %}
<p>{%block content %}
{% if post.author == user %}
  <form method="POST">
  {% csrf_token %}
  <button type="submit" class="button">Удалить объявление</button>
  </form>
   <a href="{% url 'core:post_detail' post.id %}"> Просмотр объявления</a>
   {% else %}
   <h2>Вы не можете удалить объявление!!</h2>
   <a href="{% url 'core:post_detail' post.id %}"> Просмотр объявления</a>
   <hr />
   <a href="{% url 'core:index' %}"> На главную</a>
{% endif %}
{% endblock content %}</p>

avitto/core/templates/core/post_detail.html
{% extends 'base.html' %}{% load my_filters %} {% block title %}
<title>{{page_title}}</title>
{% endblock title %}
<p>{%block content %} 
  <h1>Подробнее об оъявлении:</h1>
  <section>
    <ul>
      {% for category in categories %}
          <li>
            <a href="{% url 'core:category_detail' category.id %}"
              >{{ category.category_name }}</a
            >
          </li>
          <li>{{ category.description }}</li>
          <hr />
          {% endfor %}
    </ul>
  </section>
  <section>
    <h2>{{ post.post_name }}</h2>
    <h2>Категория объявления: {{ post.category }}</h2>
    <ul class="post_card-detail image_card">      
      <li><p> {{ post.description|linebreaks }}</p>
      <img src="{{ post.image_url }}" alt="{{ post.post_name}}" />      
      <p>Дата публикации: {{ post.date_pub }}</p>
      <p>Дата последнего изменения: {{ post.date_edit }}</p>
      <p>Объявление изменялось {{ post.date_edit|timesince }} назад</p>
      <p>Стоимость: {{ post.price|currency}} рублей</p>     
       <a href="{% url 'core:profile' post.author.id %}">Продавец: {{post.author.username}} </a>
            </a>
<!--     {% if images %}-->
<!--     {% for img in images %}-->
<!--     <p>{{ img }} <img src="{{ images.image_url  }}" alt="{{ img }}" /></p>-->
<!--     {% endfor %}-->
<!--     {% endif %}-->
   
      
          </li>        
    </ul> 
    
    
       <div >
            <h2> Комментарии </h2> 
            {% if comments.all %}
            {% for comment in comments.all %}
            <hr>
                <h3> <b> {{ comment.user.username }} </b> : {{comment.content}} </h3>
                <p> {{comment.timestamp|date:"d F G:i" }} </p>
            {% endfor %}
            {% else %}
                <h3 class='msg'> Комментариев нет. Вы можете стать первым. </h3>
            {% endif %}
            <hr>
            {% if comment_form %}
                <form method='post'>
                    <p> Комментарий: 
                    {% csrf_token %} {{comment_form.content}} </p>
                <button type='submit' class='button'> Отправить </button>
                </form>
            {% else %}
                <p style='color:red;'> Комментарии только для зарегистрированных пользователей </p>
            {% endif %}
        </div>

    <a href="{% url 'core:post_edit' post.id%}">редактировать объявление</a>
    <hr />
    <a href="{% url 'core:post_delete' post.id%}">удалить объявление</a>
    <a href="{% url 'core:post_share' post_id=post.id %}">поделиться объявлением</a>
  </section>
{% endblock content%}</p>

avitto/core/templates/core/post_edit.html
{% extends 'base.html' %} {% block title %}
<title>{{page_title}}</title>
{% endblock title %}
<p>{%block content %} 
  {% if post.author == user %}
  <form method="POST"  enctype="multipart/form-data" class="post-form_update">
    {% csrf_token %}
     {% for field in form %}
      <p>{{ field.label }}</p>
      <p>{{ field }}</p>
      {% endfor %}
    <button type="submit" class="button">обновить объявление</button>
  </form>
 {% else %}
  <h2>Вы не можете редактировать это объявление!!</h2>
  {% endif %}
{% endblock content%}</p>

avitto/core/templates/core/post_gallery.html
{% extends 'base.html' %} {% block title %}
<title>{{page_title}}</title>
{% endblock title %}
<p>{%block content %}
<p>фотки</p>
{{ images }}
  
{% endblock content%}</p>

avitto/core/templates/core/share.html
{% extends 'base.html' %} 
{% block title %}
<title>поделиться объявлением</title>
{% endblock title %}
<p>{%block content %}
  <header>
      <h1>поделиться объявлением</h1>
    </header>
    <!-- /Header -->
    <section>
      {% if sent %}
      <h2>E-mail успешно отправлен </h2>
      <p>{{post.post_name}} Был успешно отправлен {{form.cleaned_data.to}}</p>
      {% else %}
      <h2>Отправить объявление {{post.post_name}} на e-mail</h2>
      <form method='post' action='.'>
      
        {% csrf_token %} 
         <p>{{ field.errors }}</p>
         <p>{{ form.as_p }}</p>
         <button type="submit" class="button">Отправить объявление</button>
        </form>
          
        {% endif %}
    </section>     
{% endblock content%}</p>